{% set name = "nicelib" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/NiceLib-{{ version }}.zip
  sha256: 74512ca5f41f99370ea157c2a0b55435e9b17755dbd7cce23cd753bc0bb2481f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - cffi >=1.5
    - pycparser
    - future

test:
  imports:
    - nicelib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mabuchilab/NiceLib
  summary: A package for rapidly developing "nice" Python bindings to C libraries, using `cffi`
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://nicelib.readthedocs.io/
  dev_url: https://github.com/mabuchilab/NiceLib

extra:
  recipe-maintainers:
    - beenje
